package com.ruse.world.allornothing;

public enum Types {

	GAMBLE_DC, DONATION_ITEM, UGRADE_CHEST, BARROWS_CHEST, ENTRIES_REFUND, BLACK_JACK_DC, WHEEL_REWARD, MISC,
	ROULETTE_DC, AON_BOX, GOLDEN_SCRATCH_CARD, RARE_SCRATCH_CARD, DYNAMIC_SCRATCH_CARD, COINFLIP_DC

}